### ISSUE TITLE
Patient DOB display

### ISSUE THREAD

**Issue by EmilyDev** [jakepeyser/steps#115]
Patient DOB displays with Time zone on create plan page. Cannot splice the string or format it. Stackoverflow suggests creating a Gettermethod on Sequelize model

**Comment by jakepeyser** [comment]
Can we just use [moment.js](http://momentjs.com/) like I did in [PatientPlan](https://github.com/jakepeyser/steps/blob/master/app/components/plan/PatientPlan.js#L18-L19)?
