### ISSUE TITLE
Patient Dashboard

### ISSUE THREAD

**Issue by jakepeyser** [jakepeyser/steps#36]
Display stats in "cards" at the top of the patient's dashboard:
- incomplete exercises (for today)

**Comment by Hitenp1** [comment]
![dashboard sketch 1](https://cloud.githubusercontent.com/assets/20926605/20496254/6fffc0b8-aff2-11e6-9afe-2c708f62f58e.jpg)

**Comment by jakepeyser** [comment]
## Ideas
- [Dual axis dot plot with variable plot size](https://www.theguardian.com/world/interactive/2013/feb/12/state-of-the-union-reading-level)
- [Dot line chart](http://recharts.org/examples#CustomizedDotLineChart)

**Comment by jakepeyser** [comment]
https://www.youtube.com/watch?v=GPXfZK9R5mw&feature=em-subs_digest
