### ISSUE TITLE
Create exercise plan Sketch

### ISSUE THREAD

**Issue by jakepeyser** [jakepeyser/steps#47]

**Comment by jakepeyser** [comment]
### Desktop
![desktop](https://cloud.githubusercontent.com/assets/1534503/20465757/27e02274-af33-11e6-9091-8a72388599fe.png)
- breadcrumbs on top
- patient view in right column
- all field required except note sections
- add button opens a [Popover](http://www.material-ui.com/#/components/popover) to allow the selection of 'New' or an existing treatment from the list of the therapist's exercises
- add button is disabled while required info is missing from existing treatments

**Comment by jakepeyser** [comment]
### Mobile
![tablet](https://cloud.githubusercontent.com/assets/1534503/20466039/c87d6a48-af38-11e6-8dc9-ad5a28e2ec2c.png)
- same as desktop, but compress fields and remove profile info

**Comment by jakepeyser** [comment]
### Mobile
![mobile](https://cloud.githubusercontent.com/assets/1534503/20466042/e213fde6-af38-11e6-82b0-edaf2718d694.png)
- remove breadcrumbs and replace with title
- compress fields more
Note: This will be painful on mobile, but is unavoidable unless we want to split screens or go native

**Comment by mkewls** [comment]
Re: Mobile, agreed that we definitely need to consider how we make it more friendly. I'm ok with both compression and 'two screen' form flow, depending on whether compression of fields gets out of hand.
