### ISSUE TITLE
Issue with Patient creation

### ISSUE THREAD

**Issue by jakepeyser** [jakepeyser/steps#73]
As of https://github.com/jakepeyser/therapy/commit/179c41722c742462e414b1235606fb0ac966f4d2, when you attempt to create a new Patient without a password in the input object, you receive the error `data and salt arguments required`. This is an issue as doctors will be creating patients w/o explicit passwords.

**Possible solution**: Default the password to a random alphanumeric string of 6 characters which will subsequently be sent to the user as their temp password. They can then log in and change their password when setting up their account.

**Comment by mkewls** [comment]
Closed with #75 Mods
