### ISSUE TITLE
Design Patient Plan View (+Confirmation Page)

### ISSUE THREAD

**Issue by mkewls** [jakepeyser/steps#86]

**Comment by jakepeyser** [comment]
# [Plan Confirmation](https://drive.google.com/drive/folders/0B74g2zDubN9jdmR1YXB5U25hZEk)
This is the subsequent page to where a therapist creates a plan. They are able to view the treatments in a more condensed format and choose to finalize the plan or edit it once again.

### Desktop
![desktop](https://cloud.githubusercontent.com/assets/1534503/20510408/156a9032-b03e-11e6-8fdf-f83de5098c51.png)

### Tablet
![tablet](https://cloud.githubusercontent.com/assets/1534503/20510425/35cfe5a2-b03e-11e6-9909-1824a3a9f5bc.png)

### Mobile
![mobile](https://cloud.githubusercontent.com/assets/1534503/20510432/47f32b86-b03e-11e6-88e7-81676ba8b997.png)
- removes the exercise description in favor of more space for the treatment details
- number is now inlayed within the image

**Comment by jakepeyser** [comment]
# [Patient Plan](https://drive.google.com/drive/folders/0B74g2zDubN9jYjNrY2piWVMzUUk)
This is the patient's home page where they can see their current plan and initiate any one of their uncompleted treatments for the day. IEach treatment indicates whether it has completed that current day, along with the corresponding pain level if recorded.

### Desktop
![desktop](https://cloud.githubusercontent.com/assets/1534503/20510499/aa09fdfe-b03e-11e6-8e69-5a3301fd1bbf.png)
- completed treatments are grayed out or given lower opacity level
- the 'start exercise' button becomes an emoticon corresponding to the logged pain level

### Tablet
![tablet](https://cloud.githubusercontent.com/assets/1534503/20510512/cd15c864-b03e-11e6-882a-41a6ad524af7.png)
- notice the new navbar for patients

### Mobile
![mobile](https://cloud.githubusercontent.com/assets/1534503/20510515/dff71820-b03e-11e6-817a-85bec58c6a3b.png)
- notice the new menu bar for patients
- the 'start workout' and pain indicators have now moved to an image overlay as we do not want to block the treatment details. open to other suggestions that compromises ton that decision

**Comment by mkewls** [comment]
They look great. Really nice. Two comments: (1) I think you should move the signal the state of the page to the therapist in the 'finalization' view. Suggest a title (e.g., 'Finalize') and placement of the buttons (in desktop view) toward the top with the labels 'Send to Patient' & 'Keep Editing'. (2) I really think we'll have to split out the treatment rows in mobile view so that the videos are atop/beneath the treatment description, or alternatively, hidden entirely. The text will just be too small too read otherwise.

**Comment by jakepeyser** [comment]
Updates:
- [ ] Remove breadcrumbs and create header
- [ ] Incl. desc and addl notes on desktop and tablet
- [ ] On mobile, make each treatment `flex-direction: vertical`
- [ ] Change to notes on desktop for patient plan
- [ ] Remove paragraph text on tablet for patient plan

**Comment by jakepeyser** [comment]
Changes made and images in above comment and Google Drive updated
